#!/bin/bash
# Universal Overnight Autonomous Session Runner v2
# Generated by /overnight skill — do not edit manually
#
# v2 improvements:
# - Push after every commit (data safety)
# - Draft PR after first commit (remote visibility)
# - Severity-based iteration budget
# - Token tracking in progress.md
# - Resume from remote branch
# - Categorized commit messages

# --- Configuration ---
OVERNIGHT_DIR=".planning/overnight"
MANIFEST="$OVERNIGHT_DIR/manifest.json"
PROGRESS="$OVERNIGHT_DIR/progress.md"
PROMPT="$OVERNIGHT_DIR/PROMPT.md"
RESULTS_DIR="$OVERNIGHT_DIR/results"
MAX_ITERATIONS=30
NO_PROGRESS_LIMIT=3
ERROR_LIMIT=5

# --- Pre-flight checks ---
command -v python3 >/dev/null || { echo "ERROR: python3 required"; exit 1; }
command -v claude >/dev/null || { echo "ERROR: claude CLI required"; exit 1; }

# --- Resume from remote branch if local files missing ---
BRANCH_FROM_REMOTE=""
if [ ! -f "$MANIFEST" ]; then
  echo "No local manifest found. Checking remote branches..."
  BRANCH_FROM_REMOTE=$(git branch -r 2>/dev/null | grep "origin/overnight/" | sort -r | head -1 | tr -d ' ')
  if [ -n "$BRANCH_FROM_REMOTE" ]; then
    LOCAL_BRANCH="${BRANCH_FROM_REMOTE#origin/}"
    echo "Found remote branch: $LOCAL_BRANCH"
    read -p "Resume from this branch? [y/N] " confirm
    if [[ "$confirm" =~ ^[Yy] ]]; then
      git fetch origin "$LOCAL_BRANCH"
      git checkout "$LOCAL_BRANCH" 2>/dev/null || git checkout -b "$LOCAL_BRANCH" "$BRANCH_FROM_REMOTE"
      echo "Resumed on branch $LOCAL_BRANCH"
    else
      echo "ERROR: No manifest found and remote resume declined. Run /overnight first."
      exit 1
    fi
  else
    echo "ERROR: Missing $MANIFEST — run /overnight first"
    exit 1
  fi
fi

for f in "$MANIFEST" "$PROMPT" "$PROGRESS"; do
  [ -f "$f" ] || { echo "ERROR: Missing $f — run /overnight first"; exit 1; }
done

python3 -c "import json; json.load(open('$MANIFEST'))" 2>/dev/null \
  || { echo "ERROR: manifest.json is not valid JSON"; exit 1; }

mkdir -p "$RESULTS_DIR"

# --- Read validation commands from manifest ---
TYPECHECK_CMD=$(python3 -c "import json; d=json.load(open('$MANIFEST')); print(d.get('validation_commands',{}).get('typecheck','echo no-typecheck'))")
BUILD_CMD=$(python3 -c "import json; d=json.load(open('$MANIFEST')); print(d.get('validation_commands',{}).get('build','echo no-build'))")

# --- Read never-touch patterns ---
NEVER_TOUCH=$(python3 -c "
import json
d = json.load(open('$MANIFEST'))
for p in d.get('never_touch', []):
    print(p)
")

# --- State ---
iteration=0
no_progress_count=0
error_count=0
pr_created=false

# --- Prevent macOS sleep ---
caffeinate -is -w $$ &
CAFFEINATE_PID=$!

# --- Heartbeat ---
echo "$iteration" > "$OVERNIGHT_DIR/.current_iteration"
(while true; do
  iter=$(cat "$OVERNIGHT_DIR/.current_iteration" 2>/dev/null || echo "?")
  echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) — iteration $iter" \
    >> "$OVERNIGHT_DIR/heartbeat.log"
  sleep 300
done) &
HEARTBEAT_PID=$!

# --- Cleanup on exit ---
cleanup() {
  kill $CAFFEINATE_PID 2>/dev/null || true
  kill $HEARTBEAT_PID 2>/dev/null || true
  echo "" >> "$PROGRESS"
  echo "## Session ended at $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$PROGRESS"
  echo "Total iterations: $iteration" >> "$PROGRESS"

  # Final push on exit
  git push origin "$BRANCH" 2>/dev/null || true

  osascript -e 'display notification "Overnight session complete — check progress.md" with title "Overnight"' 2>/dev/null || true
}
trap cleanup EXIT

# --- Pre-flight summary ---
echo "=== Overnight Autonomous Session v2 ==="
echo "Started: $(date)"
echo "Manifest: $(python3 -c "
import json; d=json.load(open('$MANIFEST'))
print(f\"{len(d['tasks'])} tasks | critical: {sum(1 for t in d['tasks'] if t['severity']=='critical')} | high: {sum(1 for t in d['tasks'] if t['severity']=='high')}\")
")"
echo "Max iterations: $MAX_ITERATIONS"
echo ""

# --- Create or reuse branch ---
BRANCH=$(python3 -c "import json; print(json.load(open('$MANIFEST')).get('branch', 'overnight/session'))")
if git rev-parse --verify "$BRANCH" >/dev/null 2>&1; then
  echo "Resuming on existing branch: $BRANCH"
  git checkout "$BRANCH"
else
  echo "Creating new branch: $BRANCH"
  git checkout -b "$BRANCH" || { echo "ERROR: Could not create branch"; exit 1; }
fi
git push -u origin "$BRANCH" 2>/dev/null || echo "WARN: Could not push branch (will try after first commit)"

# === Main Loop ===
while [ $iteration -lt $MAX_ITERATIONS ]; do
  iteration=$((iteration + 1))
  echo "$iteration" > "$OVERNIGHT_DIR/.current_iteration"
  echo ""
  echo "=== Iteration $iteration / $MAX_ITERATIONS === $(date -u +%Y-%m-%dT%H:%M:%SZ)"

  # --- Validate manifest JSON ---
  if ! python3 -c "import json; json.load(open('$MANIFEST'))" 2>/dev/null; then
    echo "WARN: manifest.json corrupted — restoring from git"
    git checkout -- "$MANIFEST"
  fi

  # --- Read task stats ---
  stats=$(python3 -c "
import json
d = json.load(open('$MANIFEST'))
tasks = d['tasks']
pending = sum(1 for t in tasks if t['status'] == 'pending')
completed = sum(1 for t in tasks if t['status'] == 'completed')
escalated = sum(1 for t in tasks if t['status'] == 'escalated')
failed = sum(1 for t in tasks if t['status'] == 'failed')
total = len(tasks)
print(f'{pending},{completed},{escalated},{failed},{total}')
" 2>/dev/null) || {
    echo "ERROR: Could not read manifest"
    error_count=$((error_count + 1))
    if [ $error_count -ge $ERROR_LIMIT ]; then
      echo "ERROR LIMIT reached. Stopping."
      break
    fi
    sleep 30
    continue
  }

  pending=$(echo "$stats" | cut -d, -f1)
  completed=$(echo "$stats" | cut -d, -f2)
  escalated=$(echo "$stats" | cut -d, -f3)
  failed=$(echo "$stats" | cut -d, -f4)
  total=$(echo "$stats" | cut -d, -f5)

  echo "Tasks: $pending pending, $completed completed, $escalated escalated, $failed failed (of $total)"

  # --- Check completion ---
  if [ "$pending" -eq 0 ]; then
    echo "All tasks addressed. Session complete."
    break
  fi

  # --- Severity-based iteration budget ---
  # First 60%: critical + high only
  # 60-80%: add medium
  # 80-100%: add low
  progress_pct=$((iteration * 100 / MAX_ITERATIONS))
  if [ $progress_pct -le 60 ]; then
    SEVERITY_FILTER="critical,high"
  elif [ $progress_pct -le 80 ]; then
    SEVERITY_FILTER="critical,high,medium"
  else
    SEVERITY_FILTER="critical,high,medium,low"
  fi

  # --- Capture git state ---
  git_sha_before=$(git rev-parse HEAD)

  # --- Build system prompt ---
  sys_prompt="Iteration $iteration/$MAX_ITERATIONS. Tasks: $pending pending, $completed completed, $escalated escalated, $failed failed (of $total). No-progress: $no_progress_count/$NO_PROGRESS_LIMIT. Severity budget: $SEVERITY_FILTER (pick tasks matching these severities first; only pick lower severity if no matching tasks remain)."

  # --- Launch Claude session ---
  output=$(claude -p "$(cat "$PROMPT")" \
    --permission-mode bypassPermissions \
    --allowedTools "Agent,Bash,Read,Write,Edit,Grep,Glob,SendMessage,MultiEdit" \
    --output-format json \
    --append-system-prompt "$sys_prompt" \
    --model sonnet \
    2>&1) || true

  # --- Parse output and extract token usage ---
  is_error=$(echo "$output" | python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
    print(d.get('is_error', True))
except:
    print('True')
" 2>/dev/null)

  # Track token usage
  tokens_used=$(echo "$output" | python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
    u = d.get('usage', {})
    print(u.get('input_tokens', 0) + u.get('output_tokens', 0))
except:
    print('0')
" 2>/dev/null)
  echo "**Tokens used this iteration:** ~$tokens_used" >> "$OVERNIGHT_DIR/.token_log"

  # --- Handle errors with exponential backoff ---
  if [ "$is_error" = "True" ]; then
    error_count=$((error_count + 1))
    backoff=$((30 * error_count))
    [ $backoff -gt 300 ] && backoff=300
    echo "ERROR: Claude session failed (error $error_count/$ERROR_LIMIT). Waiting ${backoff}s."

    if [ $error_count -ge $ERROR_LIMIT ]; then
      echo "ERROR LIMIT: $ERROR_LIMIT consecutive errors. Stopping."
      echo "## Error Limit Reached" >> "$PROGRESS"
      echo "Stopped after $iteration iterations — $ERROR_LIMIT consecutive errors." >> "$PROGRESS"
      break
    fi

    sleep $backoff
    continue
  fi

  # Reset error count on success
  error_count=0

  # --- Post-iteration safety checks ---
  git_sha_after=$(git rev-parse HEAD)

  # 1. Never-touch enforcement
  if [ "$git_sha_before" != "$git_sha_after" ]; then
    changed_files=$(git diff --name-only "$git_sha_before".."$git_sha_after")
    violation=""
    while IFS= read -r pattern; do
      [ -z "$pattern" ] && continue
      if echo "$changed_files" | grep -q "$pattern"; then
        violation="$pattern"
        break
      fi
    done <<< "$NEVER_TOUCH"

    if [ -n "$violation" ]; then
      echo "SAFETY: Never-touch file modified ($violation). Reverting iteration."
      git reset --hard "$git_sha_before"
      echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) — Reverted iteration $iteration: never-touch violation ($violation)" \
        >> "$OVERNIGHT_DIR/REVERTED.md"
      no_progress_count=$((no_progress_count + 1))
      sleep 5
      continue
    fi
  fi

  # 2. Build validation (don't trust Claude to revert)
  if [ "$git_sha_before" != "$git_sha_after" ]; then
    if ! eval "$TYPECHECK_CMD" > /dev/null 2>&1; then
      echo "SAFETY: Typecheck failed after iteration. Reverting."
      git reset --hard "$git_sha_before"
      echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) — Reverted iteration $iteration: typecheck failure" \
        >> "$OVERNIGHT_DIR/REVERTED.md"
      no_progress_count=$((no_progress_count + 1))
      sleep 5
      continue
    fi

    if ! eval "$BUILD_CMD" > /dev/null 2>&1; then
      echo "SAFETY: Build failed after iteration. Reverting."
      git reset --hard "$git_sha_before"
      echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) — Reverted iteration $iteration: build failure" \
        >> "$OVERNIGHT_DIR/REVERTED.md"
      no_progress_count=$((no_progress_count + 1))
      sleep 5
      continue
    fi
  fi

  # 3. Progress detection
  if [ "$git_sha_before" = "$git_sha_after" ]; then
    no_progress_count=$((no_progress_count + 1))
    echo "No git changes. No-progress: $no_progress_count/$NO_PROGRESS_LIMIT"
  else
    no_progress_count=0
    echo "Progress made:"
    git log --oneline "$git_sha_before".."$git_sha_after"

    # === IMPROVEMENT #1: Push after every successful commit ===
    git push origin "$BRANCH" 2>/dev/null || echo "WARN: Could not push (will retry next iteration)"

    # === IMPROVEMENT #8: Create draft PR after first successful commit ===
    if [ "$pr_created" = false ] && command -v gh >/dev/null 2>&1; then
      gh pr create \
        --title "chore: overnight session" \
        --body "$(cat <<PREOF
## Overnight Autonomous Session (in progress)

**Branch:** $BRANCH
**Started:** $(date -u +%Y-%m-%dT%H:%M:%SZ)

This PR is updated automatically as the overnight session progresses.

### Review when complete
- [ ] Check \`.planning/overnight/MORNING-REVIEW.md\` for items needing your decision
- [ ] Review the diff for correctness
- [ ] Run the test suite manually

### Files
- Progress log: \`.planning/overnight/progress.md\`
- Morning review: \`.planning/overnight/MORNING-REVIEW.md\`
- Reverted changes: \`.planning/overnight/REVERTED.md\`
PREOF
)" --draft 2>/dev/null && {
        pr_created=true
        echo "Draft PR created."
      } || echo "WARN: Could not create draft PR"
    fi
  fi

  # --- Circuit breaker ---
  if [ $no_progress_count -ge $NO_PROGRESS_LIMIT ]; then
    echo "CIRCUIT BREAKER: $NO_PROGRESS_LIMIT iterations with no progress. Stopping."
    echo "## Circuit Breaker Triggered" >> "$PROGRESS"
    echo "Stopped after $iteration iterations — no progress for last $NO_PROGRESS_LIMIT." >> "$PROGRESS"
    break
  fi

  sleep 5
done

# === Post-loop ===

# --- Final validation ---
echo ""
echo "=== Final Validation ==="
eval "$TYPECHECK_CMD" && echo "Types: PASS" || echo "Types: FAIL"
eval "$BUILD_CMD" && echo "Build: PASS" || echo "Build: FAIL"

# --- Token summary ---
total_tokens=0
if [ -f "$OVERNIGHT_DIR/.token_log" ]; then
  total_tokens=$(python3 -c "
import re
total = 0
for line in open('$OVERNIGHT_DIR/.token_log'):
    m = re.search(r'~(\d+)', line)
    if m: total += int(m.group(1))
print(total)
" 2>/dev/null || echo "0")
  echo "" >> "$PROGRESS"
  echo "## Token Usage" >> "$PROGRESS"
  echo "**Total tokens:** ~$total_tokens (~\$$(python3 -c "print(f'{$total_tokens * 0.000003:.2f}')" 2>/dev/null || echo '?') at Sonnet rates)" >> "$PROGRESS"
fi

# --- Read final stats ---
pending_final=$(python3 -c "import json; d=json.load(open('$MANIFEST')); print(sum(1 for t in d['tasks'] if t['status']=='pending'))" 2>/dev/null || echo "?")
completed_final=$(python3 -c "import json; d=json.load(open('$MANIFEST')); print(sum(1 for t in d['tasks'] if t['status']=='completed'))" 2>/dev/null || echo "?")
escalated_final=$(python3 -c "import json; d=json.load(open('$MANIFEST')); print(sum(1 for t in d['tasks'] if t['status']=='escalated'))" 2>/dev/null || echo "?")

# --- Final push ---
echo ""
echo "=== Final Push ==="
git push origin "$BRANCH" 2>/dev/null || echo "WARN: Could not push branch"

# --- Update PR title with final stats (if PR exists) ---
if [ "$pr_created" = true ] && command -v gh >/dev/null 2>&1; then
  gh pr edit --title "chore: overnight session — $completed_final fixes" 2>/dev/null || true
fi

# --- Create PR if not yet created ---
if [ "$pr_created" = false ] && command -v gh >/dev/null 2>&1; then
  gh pr create \
    --title "chore: overnight session — $completed_final fixes" \
    --body "$(cat <<EOF
## Overnight Autonomous Session

**Iterations:** $iteration
**Tasks:** $completed_final completed, $escalated_final escalated, $pending_final still pending
**Tokens:** ~$total_tokens

### Review Checklist
- [ ] Check \`.planning/overnight/MORNING-REVIEW.md\` for items needing your decision
- [ ] Review the diff for correctness
- [ ] Run the test suite manually

### Files
- Progress log: \`.planning/overnight/progress.md\`
- Morning review: \`.planning/overnight/MORNING-REVIEW.md\`
- Reverted changes: \`.planning/overnight/REVERTED.md\`
EOF
)" 2>/dev/null && echo "PR created successfully." || echo "WARN: Could not create PR — create manually from branch $BRANCH"
fi

# --- Final summary ---
echo ""
echo "=== Overnight Session Complete ==="
echo "Branch: $BRANCH"
echo "Iterations: $iteration"
echo "Completed: $completed_final | Escalated: $escalated_final | Pending: $pending_final"
echo "Tokens: ~$total_tokens"
echo ""
echo "Next steps:"
echo "  1. Review: .planning/overnight/MORNING-REVIEW.md"
echo "  2. Check the PR"
echo "  3. Merge when satisfied"
